# Generated by Django 2.1.4 on 2019-06-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0003_auto_20190612_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='C:\\Users\\USER\\Desktop\\Django\\takmyo\\static\\image\\unknown_icon.png', null=True, upload_to='profileImage/'),
        ),
    ]
