# Generated by Django 2.1.4 on 2019-06-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0007_auto_20190617_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='lng',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('review', 'Review'), ('form', 'Form')], max_length=30, null=True),
        ),
    ]
