# Generated by Django 2.1.4 on 2019-06-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0008_auto_20190619_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='detail_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='extra_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
