# Generated by Django 2.1.4 on 2019-06-22 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0009_auto_20190619_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catsitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=100)),
                ('catsitter_profile_image', models.ImageField(default='unknown_icon.png', upload_to='catsitter_profileImage/')),
                ('rate', models.FloatField(blank=True, default=0.0)),
                ('have_pet', models.BooleanField(default=False)),
                ('have_pet_experience', models.BooleanField(default=False)),
                ('have_care_experience', models.BooleanField(default=False)),
                ('available_pill', models.BooleanField(default=False)),
                ('available_identification', models.BooleanField(default=False)),
                ('available_visit', models.BooleanField(default=False)),
                ('available_consignment', models.BooleanField(default=False)),
                ('visit_price_per_once', models.IntegerField(default=0)),
                ('visit_price_per_extra_cat', models.IntegerField(default=0)),
                ('consignment_price_per_one_day', models.IntegerField(default=0)),
                ('consignment_price_per_one_week', models.IntegerField(default=0)),
                ('consignment_price_per_one_month', models.IntegerField(default=0)),
                ('consignment_price_per_extra_cat', models.IntegerField(default=0)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('available_weekday_am', models.BooleanField(default=False)),
                ('available_weekday_pm', models.BooleanField(default=False)),
                ('available_weekend_am', models.BooleanField(default=False)),
                ('available_weekend_pm', models.BooleanField(default=False)),
                ('introduce', models.TextField(default='')),
                ('warning', models.TextField(default='')),
                ('available_region', models.TextField(default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-register_date'],
            },
        ),
        migrations.CreateModel(
            name='Catsitter_promotion_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_image', models.ImageField(default='unknown_icon.png', upload_to='catsitter_promotionImage/')),
                ('catsitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catsitter_promotion_image', to='takmyo_app.Catsitter')),
            ],
        ),
    ]
