# Generated by Django 2.1.4 on 2019-06-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0010_catsitter_catsitter_promotion_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catsitter',
            old_name='available_consignment',
            new_name='activation',
        ),
        migrations.RemoveField(
            model_name='catsitter',
            name='available_visit',
        ),
        migrations.RemoveField(
            model_name='catsitter',
            name='available_weekday_am',
        ),
        migrations.RemoveField(
            model_name='catsitter',
            name='available_weekday_pm',
        ),
        migrations.RemoveField(
            model_name='catsitter',
            name='available_weekend_am',
        ),
        migrations.RemoveField(
            model_name='catsitter',
            name='available_weekend_pm',
        ),
        migrations.AddField(
            model_name='catsitter',
            name='available_day',
            field=models.CharField(choices=[('weekend', 'Weekend'), ('weekday', 'Weekday'), ('both', 'Both')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='available_place',
            field=models.CharField(choices=[('visit', 'Visit'), ('consignment', 'Consignment'), ('both', 'Both')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='available_weekday_time',
            field=models.CharField(choices=[('pm', 'Pm'), ('both', 'Both'), ('am', 'Am')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='available_weekend_time',
            field=models.CharField(choices=[('pm', 'Pm'), ('both', 'Both'), ('am', 'Am')], default='', max_length=10),
        ),
    ]
