# Generated by Django 2.1.4 on 2019-06-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0011_auto_20190623_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catsitter',
            old_name='rate',
            new_name='rate_per_five',
        ),
        migrations.AddField(
            model_name='catsitter',
            name='rate_per_hundred',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_day',
            field=models.CharField(choices=[('both', 'Both'), ('weekday', 'Weekday'), ('weekend', 'Weekend')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_place',
            field=models.CharField(choices=[('both', 'Both'), ('visit', 'Visit'), ('consignment', 'Consignment')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekday_time',
            field=models.CharField(choices=[('am', 'Am'), ('pm', 'Pm'), ('both', 'Both')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekend_time',
            field=models.CharField(choices=[('am', 'Am'), ('pm', 'Pm'), ('both', 'Both')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('form', 'Form'), ('review', 'Review')], max_length=30, null=True),
        ),
    ]
