# Generated by Django 2.1.4 on 2019-06-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0013_auto_20190626_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='catsitter',
            name='available_change_consignment_price_per_extra_cat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='available_change_visit_price_per_extra_cat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_day',
            field=models.CharField(choices=[('both', 'Both'), ('weekend', 'Weekend'), ('weekday', 'Weekday')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_place',
            field=models.CharField(choices=[('both', 'Both'), ('visit', 'Visit'), ('consignment', 'Consignment')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekday_time',
            field=models.CharField(choices=[('am', 'Am'), ('both', 'Both'), ('pm', 'Pm')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekend_time',
            field=models.CharField(choices=[('am', 'Am'), ('both', 'Both'), ('pm', 'Pm')], default='', max_length=10),
        ),
    ]
