# Generated by Django 2.1.4 on 2019-07-01 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0015_auto_20190630_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='catsitterreview',
            name='catee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catee_reviews', to='takmyo_app.Catee'),
        ),
        migrations.AlterField(
            model_name='cateetocatsitterform',
            name='place',
            field=models.CharField(choices=[('visit', 'Visit'), ('consignment', 'Consignment')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cateetocatsitterform',
            name='state',
            field=models.CharField(choices=[('unrecognized', 'Unrecognized'), ('progress', 'Progress'), ('recognized', 'Recognized')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_day',
            field=models.CharField(choices=[('both', 'Both'), ('weekday', 'Weekday'), ('weekend', 'Weekend')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_place',
            field=models.CharField(choices=[('visit', 'Visit'), ('both', 'Both'), ('consignment', 'Consignment')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekday_time',
            field=models.CharField(choices=[('am', 'Am'), ('both', 'Both'), ('pm', 'Pm')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekend_time',
            field=models.CharField(choices=[('am', 'Am'), ('both', 'Both'), ('pm', 'Pm')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitterreview',
            name='catsitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catsitter_reviews', to='takmyo_app.Catsitter'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('form', 'Form'), ('review', 'Review')], max_length=30, null=True),
        ),
    ]
