# Generated by Django 2.1.4 on 2019-07-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0016_auto_20190701_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='catsitterreview',
            name='total_rate_per_hundred',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cateetocatsitterform',
            name='place',
            field=models.CharField(choices=[('consignment', 'Consignment'), ('visit', 'Visit')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cateetocatsitterform',
            name='state',
            field=models.CharField(choices=[('unrecognized', 'Unrecognized'), ('recognized', 'Recognized'), ('progress', 'Progress')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_day',
            field=models.CharField(choices=[('weekday', 'Weekday'), ('weekend', 'Weekend'), ('both', 'Both')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_place',
            field=models.CharField(choices=[('both', 'Both'), ('consignment', 'Consignment'), ('visit', 'Visit')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekday_time',
            field=models.CharField(choices=[('pm', 'Pm'), ('both', 'Both'), ('am', 'Am')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekend_time',
            field=models.CharField(choices=[('pm', 'Pm'), ('both', 'Both'), ('am', 'Am')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('review', 'Review'), ('form', 'Form')], max_length=30, null=True),
        ),
    ]
