# Generated by Django 2.1.4 on 2019-07-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0017_auto_20190701_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='catsitter',
            name='achievement_rate_per_five',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='achievement_rate_per_hundred',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='kindness_rate_per_five',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='kindness_rate_per_hundred',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='time_rate_per_five',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='catsitter',
            name='time_rate_per_hundred',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cateetocatsitterform',
            name='state',
            field=models.CharField(choices=[('recognized', 'Recognized'), ('unrecognized', 'Unrecognized'), ('progress', 'Progress')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_day',
            field=models.CharField(choices=[('weekend', 'Weekend'), ('weekday', 'Weekday'), ('both', 'Both')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_place',
            field=models.CharField(choices=[('consignment', 'Consignment'), ('visit', 'Visit'), ('both', 'Both')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekday_time',
            field=models.CharField(choices=[('am', 'Am'), ('pm', 'Pm'), ('both', 'Both')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekend_time',
            field=models.CharField(choices=[('am', 'Am'), ('pm', 'Pm'), ('both', 'Both')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='rate_per_five',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='rate_per_hundred',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('form', 'Form'), ('review', 'Review')], max_length=30, null=True),
        ),
    ]
