# Generated by Django 2.1.4 on 2019-07-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0018_auto_20190701_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateetocatsitterform',
            name='place',
            field=models.CharField(choices=[('visit', 'Visit'), ('consignment', 'Consignment')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cateetocatsitterform',
            name='state',
            field=models.CharField(choices=[('progress', 'Progress'), ('unrecognized', 'Unrecognized'), ('recognized', 'Recognized')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_day',
            field=models.CharField(choices=[('weekday', 'Weekday'), ('both', 'Both'), ('weekend', 'Weekend')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_place',
            field=models.CharField(choices=[('visit', 'Visit'), ('both', 'Both'), ('consignment', 'Consignment')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekday_time',
            field=models.CharField(choices=[('am', 'Am'), ('both', 'Both'), ('pm', 'Pm')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekend_time',
            field=models.CharField(choices=[('am', 'Am'), ('both', 'Both'), ('pm', 'Pm')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitterreview',
            name='achievement_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='catsitterreview',
            name='kindness_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='catsitterreview',
            name='time_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='catsitterreview',
            name='total_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
