# Generated by Django 2.1.4 on 2019-07-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0019_auto_20190704_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='feature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='hospital',
            field=models.CharField(blank=True, default='unknown', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='warning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cateetocatsitterform',
            name='state',
            field=models.CharField(choices=[('progress', 'Progress'), ('recognized', 'Recognized'), ('unrecognized', 'Unrecognized')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_day',
            field=models.CharField(choices=[('weekend', 'Weekend'), ('both', 'Both'), ('weekday', 'Weekday')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('review', 'Review'), ('form', 'Form')], max_length=30, null=True),
        ),
    ]
