# Generated by Django 2.1.4 on 2019-07-10 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0020_auto_20190707_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cateetocatsitterform',
            name='place',
            field=models.CharField(choices=[('consignment', 'Consignment'), ('visit', 'Visit')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cateetocatsitterform',
            name='state',
            field=models.CharField(choices=[('unrecognized', 'Unrecognized'), ('recognized', 'Recognized'), ('progress', 'Progress')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_day',
            field=models.CharField(choices=[('both', 'Both'), ('weekend', 'Weekend'), ('weekday', 'Weekday')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_place',
            field=models.CharField(choices=[('consignment', 'Consignment'), ('visit', 'Visit'), ('both', 'Both')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekday_time',
            field=models.CharField(choices=[('am', 'Am'), ('pm', 'Pm'), ('both', 'Both')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekend_time',
            field=models.CharField(choices=[('am', 'Am'), ('pm', 'Pm'), ('both', 'Both')], default='', max_length=10),
        ),
    ]
