# Generated by Django 2.1.4 on 2019-07-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0021_auto_20190710_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_profile_image',
            field=models.ImageField(blank=True, default='unknown_icon.png', null=True, upload_to='cat_profileImage/<django.db.models.fields.related.ForeignKey>/'),
        ),
        migrations.AlterField(
            model_name='cateetocatsitterform',
            name='state',
            field=models.CharField(choices=[('recognized', 'Recognized'), ('unrecognized', 'Unrecognized'), ('progress', 'Progress')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_day',
            field=models.CharField(choices=[('weekend', 'Weekend'), ('both', 'Both'), ('weekday', 'Weekday')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_place',
            field=models.CharField(choices=[('consignment', 'Consignment'), ('both', 'Both'), ('visit', 'Visit')], default='', max_length=20),
        ),
    ]
