# Generated by Django 2.1.4 on 2019-07-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takmyo_app', '0022_auto_20190710_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_profile_image',
            field=models.ImageField(blank=True, default='unknown_icon.png', null=True, upload_to='cat_profileImage/'),
        ),
        migrations.AlterField(
            model_name='cateetocatsitterform',
            name='state',
            field=models.CharField(choices=[('progress', 'Progress'), ('recognized', 'Recognized'), ('unrecognized', 'Unrecognized')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_day',
            field=models.CharField(choices=[('weekend', 'Weekend'), ('weekday', 'Weekday'), ('both', 'Both')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_place',
            field=models.CharField(choices=[('consignment', 'Consignment'), ('visit', 'Visit'), ('both', 'Both')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekday_time',
            field=models.CharField(choices=[('pm', 'Pm'), ('am', 'Am'), ('both', 'Both')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='available_weekend_time',
            field=models.CharField(choices=[('pm', 'Pm'), ('am', 'Am'), ('both', 'Both')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('form', 'Form'), ('review', 'Review')], max_length=30, null=True),
        ),
    ]
